[project]
name = "jax-imprl"
version = "0.1.0"
description = "A jax accelerated library for applying reinforcement learning to inspection and maintenance planning of deteriorating engineering systems."
readme = "README.md"
requires-python = ">=3.9,<3.10"
authors = [
  { name = "Prateek Bhustali", email = "p.bhustali@tudelft.nl" }
]
dependencies = [
  "numpy>=1.26.2,<2.0.0",
  "pyyaml>=6.0.1,<6.1.0",
  "gym>=0.23.1,<0.24.0",
  "notebook>=7.1.2,<8.0.0",
  "jax[cpu]>=0.4.28,<0.5.0; sys_platform == 'darwin'",
  "jax[cuda]>=0.4.28,<0.5.0; sys_platform == 'linux'",
  "chex>=0.1.84,<0.2.0",
  "gymnax>=0.0.1,<0.1.0",
  "flashbax>=0.1.2,<0.2.0",
  "wandb>=0.16.4,<0.17.0",
  "matplotlib>=3.8.2,<4.0.0",
  "seaborn>=0.13.2,<0.14.0",
]

[dependency-groups]
dev = [
  "pytest>=8.0.1,<9.0.0",
  "black>=24.3.0,<25.0.0",
]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["jax_imprl*"]
