# Environment settings
ENV_NAME: "matrix_game"
ENV_SETTING: "1-of-3_game"
ENV_KWARGS: 
  eval_env: False

# wandb settings
WANDB: True
WANDB_ENTITY: "shaktimaan"
WANDB_PROJECT: "jax_imprl"

# Logging settings
SEED: 42 # seed to generate random key
NUM_RUNS: 10 # num independent runs, it splits the random key into multiple keys
NUM_EPISODES: 50_000 # number of training episodes
LOGGING_FREQ: 100 # episodes
EVAL_FREQ: 5_000 # episodes
EVAL_EPISODES: 10_000 # episodes