ALGORITHM: DDQN

NUM_TIMESTEPS: 5_000_000
MAX_MEMORY_SIZE: 10_000
BATCH_SIZE: 64
TARGET_NETWORK_RESET: 50
DISCOUNT_FACTOR: 0.99

NETWORK_CONFIG:
    hidden_layers: [64, 64]
    optimizer: Adam
    lr_scheduler: LinearLR
    lr_initial: 0.001
    lr_final: 0.0001
    lr_total_iters: 500_000

EXPLORATION_STRATEGY:
      name: epsilon_greedy
      initial_value: 1
      final_value: 0.005
      num_steps: 500_000