ALGORITHM: JAC

MAX_MEMORY_SIZE: 10_000 # transitions
BATCH_SIZE: 64 # transitions
DISCOUNT_FACTOR: 0.8

ACTOR_CONFIG:
    hidden_layers: [64, 64]
    optimizer: Adam
    lr_scheduler: LinearLR
    lr_initial: 0.0001
    lr_final: 0.00001
    lr_total_iters: 500_000

CRITIC_CONFIG:
    hidden_layers: [64, 64]
    optimizer: Adam
    lr_scheduler: LinearLR
    lr_initial: 0.005
    lr_final: 0.0005
    lr_total_iters: 500_000

EXPLORATION_STRATEGY:
      name: epsilon_greedy
      initial_value: 1
      final_value: 0.005
      num_steps: 500_000